#!/usr/bin/env bash
# `just bar::launch` entry point: hand off to bar_debug_launcher.
#
# Linux: ensure Devtools symlinks are in place, ensure the bar-launch venv
# exists, then exec `python -m bar_launch` with the user's flags. Both the GUI
# (no flags) and the headless CLI (--play / --print-cmd / etc.) flow through
# the same entry point.
#
# WSL2: ensure BAR_DEVSYNC_DIR is set, cold-copy the Devtools sources into
# it (`scripts/sync.sh once`), then invoke the bar-launch.cmd shim
# (Windows-side Python launches the engine as a native Windows process).
# The shim is generated by `just setup::init` and lives at $BAR_DEVSYNC_DIR/bin/.
#
# Expects: DEVTOOLS_DIR (exported by the Justfile).

set -euo pipefail

# repos.sh expects REPOS_CONF / REPOS_LOCAL to be exported by the calling
# Justfile module. The launch recipe lives in bar.just where they aren't set,
# so default them here -- matching the values just/repos.just exports.
: "${REPOS_CONF:=$DEVTOOLS_DIR/repos.conf}"
: "${REPOS_LOCAL:=$DEVTOOLS_DIR/repos.local.conf}"
export REPOS_CONF REPOS_LOCAL

source "$DEVTOOLS_DIR/scripts/common.sh"
source "$DEVTOOLS_DIR/scripts/setup.sh"
source "$DEVTOOLS_DIR/scripts/repos.sh"

# True if a path looks linked-by-Devtools: a symlink (Linux) or, in the future,
# a sync target. For now Linux-only, the WSL2 case is the stub below.
preflight_symlinks() {
  local game_dir
  game_dir="$(detect_game_dir 2>/dev/null)" || true
  if [ -z "$game_dir" ]; then
    warn "Game directory not detected. Set BAR_GAME_DIR or run 'just setup::init' first."
    return 0
  fi

  local missing=()
  # game subdirs use .sdd so spring's archive scanner picks them up. Accept
  # either symlink or real dir for each (sync architectures vary by platform).
  [ -L "$game_dir/games/Beyond-All-Reason.sdd" ] || [ -d "$game_dir/games/Beyond-All-Reason.sdd" ] || missing+=("bar")
  [ -L "$game_dir/games/BYAR-Chobby.sdd" ]       || [ -d "$game_dir/games/BYAR-Chobby.sdd" ]       || missing+=("chobby")
  [ -L "$game_dir/engine/local-build" ]          || [ -d "$game_dir/engine/local-build" ]          || missing+=("engine")

  if [ "${#missing[@]}" -eq 0 ]; then
    return 0
  fi

  info "Devtools symlinks missing: ${missing[*]}"
  info "Run: just link::create ${missing[*]}"
  info "(continuing; bar-launch will still work for non-local sources like 'rapid://...:test')"
}

run_linux() {
  if ! command -v bar-launch &>/dev/null; then
    err "bar-launch not on PATH"
    info "Run 'just setup::init' (pipx-installs the launcher), or run 'pipx ensurepath' if it's already installed."
    exit 1
  fi
  local repo_path
  repo_path="$(bar_launch_repo_path)"

  # Manifest-staleness check: if pyproject.toml has been touched since the
  # install marker, bar_debug_launcher's pip deps may have changed. Editable
  # installs auto-pick-up .py edits but pinning a new dep needs a reinstall.
  # Keeping this in the launch path (not setup) so contributors who pull
  # don't have to remember to re-run setup before the launcher breaks on a
  # fresh import.
  local marker="${XDG_STATE_HOME:-$HOME/.local/state}/bar-devtools/bar-launch-installed"
  local pyproject="$repo_path/pyproject.toml"
  if [ -f "$pyproject" ] && [ -f "$marker" ] && [ "$pyproject" -nt "$marker" ]; then
    info "$(basename "$repo_path")/pyproject.toml is newer than the bar-launch install -- reinstalling"
    ensure_bar_launch_installed "$repo_path" || exit 1
  fi

  preflight_symlinks

  # Auto-inject flags from what's locally checked out, so a contributor who
  # ran `just link::create engine` doesn't also have to remember to type
  # `--engine local-build`. We only inject flags the user didn't already
  # supply -- explicit user args always win.
  local injected=()
  local user_args=("$@")
  local game_dir
  game_dir="$(detect_game_dir 2>/dev/null)" || true
  if [ -n "$game_dir" ]; then
    ensure_devmode_marker "$game_dir"
    _apply_debug_gl_if_requested "$game_dir/springsettings.cfg" "${user_args[@]}"
    if [ -e "$game_dir/engine/local-build" ] && ! _has_flag --engine "${user_args[@]}"; then
      injected+=(--engine local-build)
    fi
  fi
  # Strip our own flags so bar-launch doesn't choke on them.
  if _has_flag --debug-gl "${user_args[@]}"; then
    mapfile -d '' user_args < <(_strip_flag --debug-gl "${user_args[@]}")
  fi

  # The launcher's autodetect anchors itself on $0's directory; we want it
  # anchored on the Devtools-managed checkout, not on this script.
  cd "$repo_path"

  info "Running: bar-launch ${injected[*]:-} ${user_args[*]:-}"
  exec bar-launch "${injected[@]}" "${user_args[@]}"
}

# True if $1 (a flag like --engine) appears anywhere in the remaining args.
# Matches both "--engine X" and "--engine=X" forms.
_has_flag() {
  local needle="$1"
  shift
  local arg
  for arg in "$@"; do
    if [ "$arg" = "$needle" ] || [[ "$arg" == "$needle="* ]]; then
      return 0
    fi
  done
  return 1
}

# Pop a known boolean flag from "$@" by name. Echoes the remaining args (one
# per NUL byte). Bash arrays don't survive function returns, so the caller
# does:  mapfile -d '' filtered < <(_strip_flag --debug-gl "$@")
_strip_flag() {
  local needle="$1"; shift
  local arg
  for arg in "$@"; do
    if [ "$arg" = "$needle" ]; then continue; fi
    printf '%s\0' "$arg"
  done
}

# If --debug-gl is in the user's args, set DebugGL=1 and LogFlush=1 in the
# right springsettings.cfg before launch. The engine rewrites that cfg on
# graceful shutdown (and silently strips keys it doesn't normalise on the
# round-trip), so we re-apply every launch instead of trusting persistence.
# LogFlush=1 ensures driver-callback messages aren't lost if the engine
# crashes before the buffered writer flushes -- exactly the case we want
# logging for. springsettings_set is sourced from setup.sh.
_apply_debug_gl_if_requested() {
  local cfg="$1"; shift
  if _has_flag --debug-gl "$@"; then
    if [ -z "$cfg" ]; then
      warn "--debug-gl requested but no springsettings.cfg path resolved; skipping"
      return 0
    fi
    info "--debug-gl: setting DebugGL=1 LogFlush=1 in $cfg"
    springsettings_set "$cfg" DebugGL 1 \
      || warn "Could not set DebugGL=1; OpenGL debug callback will stay off."
    springsettings_set "$cfg" LogFlush 1 \
      || warn "Could not set LogFlush=1; log buffering may drop driver messages on crash."
  fi
}

run_wsl() {
  if [ -z "${BAR_DEVSYNC_DIR:-}" ]; then
    err "BAR_DEVSYNC_DIR not set. Run 'just setup::init' on WSL2 first."
    exit 1
  fi

  ensure_devmode_marker "$BAR_DEVSYNC_DIR"
  _apply_debug_gl_if_requested "$BAR_DEVSYNC_DIR/springsettings.cfg" "$@"

  # Strip --debug-gl from forwarded args so the Windows-side launcher /
  # spring.exe doesn't try to interpret it.
  local launch_args=()
  if _has_flag --debug-gl "$@"; then
    mapfile -d '' launch_args < <(_strip_flag --debug-gl "$@")
  else
    launch_args=("$@")
  fi

  local shim_wsl="$BAR_DEVSYNC_DIR/bin/bar-launch.cmd"
  if [ ! -f "$shim_wsl" ]; then
    err "Launcher shim missing at $shim_wsl"
    info "Regenerate: just bar::regen-shim"
    exit 1
  fi

  # Cold-copy sources before launch. We previously ran a long-lived watcher,
  # but ReadDirectoryChangesW over `\\wsl.localhost\` does not receive
  # Linux-side inotify events (Plan 9 doesn't forward them) -- the watcher
  # logged zero mirrored events across an entire dev session. The propagation
  # contributors thought they were getting was actually from cold-copy at
  # watcher startup. We made cold-copy the explicit, synchronous step here.
  bash "$DEVTOOLS_DIR/scripts/sync.sh" once \
    || { err "sync (cold copy) failed"; exit 1; }

  local shim_win
  shim_win="$(wslpath -w "$shim_wsl")"

  # printf, not the info helper: info uses `echo -e`, which interprets
  # `\b` in `...\bin\...` as a backspace and visually mangles the path.
  printf '\033[0;34m[info]\033[0m  Launching detached: %s %s\n' "$shim_win" "${launch_args[*]}"
  printf '\033[0;34m[info]\033[0m  logs:  just bar::log -- -F      (engine infolog)\n'
  printf '\033[0;34m[info]\033[0m         just bar::sync-logs -- -F (cold-copy log)\n'

  # Detach the launcher: nohup + & + disown drops the cmd.exe process
  # off this shell's job table so the Electron launcher's ~10-30s
  # graceful shutdown doesn't block our return. We deliberately do NOT
  # use `cmd.exe /c "start \"\" /B \"<shim>\""` -- the embedded "" quotes
  # there get double-escaped by WSL2 interop's argv->cmdline encoder
  # (the same bug that broke our earlier wmic invocation), and cmd.exe
  # ends up trying to execute a literal `\` as a command. With plain
  # `cmd.exe /c <shim> <args>`, each argv element is quoted separately
  # by interop -- no embedded escapes for us to write.
  #
  # cwd: jump to /mnt/c so cmd.exe gets a drive-letter cwd (the
  # "UNC paths are not supported" warning otherwise). The shim uses
  # absolute paths so any cwd works.
  ( cd /mnt/c && nohup cmd.exe /c "$shim_win" "${launch_args[@]}" </dev/null >/dev/null 2>&1 & )
  return 0
}

if is_wsl; then
  run_wsl "$@"
  exit $?
else
  run_linux "$@"
fi
